### ISSUE TITLE
 There is no 'LineRenderer' attached to the "RightHandAnchor" game object.

### ISSUE THREAD

**Issue by alitokur** [C-Through/VR-SimplePointer#1]
Hello Andrew, first I would like to thank you for your tutorials.  I have an issue with setting this up though. 

MissingComponentException: There is no 'LineRenderer' attached to the "RightHandAnchor" game object, but a script is trying to access it.
You probably need to add a LineRenderer to the game object "RightHandAnchor". Or your script needs to check if the component is attached before using it.

What should i do?

**Comment by VRwithAndrew** [comment]
It sounds like you have have accidentally placed an instance of the Pointer
script on the anchor. Everything is already packaged and setup on the
Pointer prefabs.

**Comment by alitokur** [comment]
huh my bad. thank u.
