### ISSUE TITLE
the down color doesn't change. 

### ISSUE THREAD

**Issue by alitokur** [C-Through/VR-SimplePointer#2]
hi andrew!
i have a problem with the click.
when i click the button i can see the "click" log in console but the colors does not change. according your tutorial, it should be white to gray but  i see only white. from the button inspector i changed the colors, i mean;
normal color : black
enter color : red
down color : green 
but it does not work again.  just see black and red.

![Untitled](https://user-images.githubusercontent.com/20575896/79224023-13f66b80-7e63-11ea-97bc-f94238147811.png)

edit: i realized that up,down and click are running at the same time.

**Comment by VRwithAndrew** [comment]
Are you setting the material color in the down event?

**Comment by alitokur** [comment]
i guess I couldn't, but I still can't see the gray color when I use [your code](https://www.youtube.com/watch?v=rgTshoVCZVQ) without changing any part.

**Comment by VRwithAndrew** [comment]
I don't think you understood my question. If you have a print statement for
the down event, then the event is at least working.

Do you have a line in the OnPointerDown function that sets the color of the
material? Similar to that of in the Pointer In/Out.

**Comment by alitokur** [comment]
of course event is working, btw yes i have a line to set the color.
